import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Autogenerated from the docs/ folder structure — add markdown files and they
// appear here. Swap for an explicit list when you want to control ordering.
const sidebars: SidebarsConfig = {
	docs: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
